data:

    evfile : ft1.fits
    scfile : ft2.fits
    ltcube : gc_ltcube.fits
    
binning:

    roiwidth    : 10.0
    binsz       : 0.1
    binsperdec  : 8
    
selection: 
    
    emin    : 100
    emax    : 300000
    zmax    : 90
    evclass : 128 
    evtype  : 3 
    tmin    : 378691203
    tmax    : 379123202
    filter  : null
    ra      : 266.405
    dec     : -28.9362
    
gtlike:
    edisp         : True
    irfs          : 'P8R2_SOURCE_V6' 
    edisp_disable : ['isodiff','galdiff']
    
model:
    src_roiwidth : 10.0
    galdiff      : '$FERMI_DIFFUSE_DIR/gll_iem_v07.fits' 
    isodiff      : 'iso_P8R2_SOURCE_V6_v06.txt'
    catalogs     : ['4FGL']
   