data:

    evfile: ft1.fits
    scfile: ft2.fits
    ltcube: ltcube.fits 
    
binning: 

    roiwidth: 
    binsz:
    binsperdec: 
    
selection:

    emin: 
    emax: 
    tmin: 
    tmax: 
    zmax: 90.0
    evclass: 128
    evtype: 3
    # GC Coordinates
    ra: 266.405 
    dec: -28.9362

gtlike:

    edisp: 
    irfs: 'P8R2_SOURCE_V6'
    edisp_disable: ['isodiff', 'galdiff']

model:

    src_roiwidth: 
    galdiff: '$FERMI_DIFFUSE_DIR/gll_iem_v07.fits'
    isodiff: 'iso_P8R2_SOURCE_V6_v06.txt'
    catalogs: ['4FGL']

components:

    - 
    
fileio:
        
    logfile: 